### ISSUE TITLE
Select PHP language branch

### ISSUE THREAD

**Issue by vgsystems** [billrobclark/alfred-phpdoc-search#1]
Hi, your workflow was awesome, so THANKS!

It would be more than perfect if it's possible to choose language of php's doc, it's possible?

Regards!

**Comment by billrobclark** [comment]
Thanks for your feedback. I apologize but I missed this request when you originally opened it. I think this could be possible you would need to update a variable in Alfred like es for Spanish etc. I will try to get to this update this weekend.

**Comment by billrobclark** [comment]
@vgsystems language support has been added on the latest release  [v.1.1.0](https://github.com/billrobclark/alfred-phpdoc-search/releases/tag/v1.1.0). Please check the Readme for instructions.

**Comment by billrobclark** [comment]
Closing issue as the feature has been added.

**Comment by vgsystems** [comment]
Hi @billrobclark, works perfect, checked and running ;)

Only one thing, when update the workflow(also deleting it and importing it again) the version number remains in 1.0.1 instead 1.1.0.

Thanks!
